import { beforeEach, describe, expect, it, vi } from 'vitest';
const { invoke, listen } = vi.hoisted(() => ({ invoke: vi.fn(), listen: vi.fn() }));
vi.mock('@tauri-apps/api/core', () => ({ invoke })); vi.mock('@tauri-apps/api/event', () => ({ listen }));
import { appBridge } from './bridge';
describe('appBridge registered-command contracts', () => {
  beforeEach(() => { invoke.mockReset(); listen.mockReset(); invoke.mockResolvedValue(undefined); listen.mockResolvedValue(() => undefined); });
  it('invokes every exposed command with its registered name and payload', async () => { const onboarding = { deviceName: 'Desk', receiveDirectory: 'C:\\In' }; const settings = { receivingEnabled: false }; const pairing = { remoteName: 'Laptop', publicKey: [1, 2], certificateFingerprint: 'fp' }; await appBridge.getAppSnapshot(); await appBridge.chooseFiles(); await appBridge.chooseDirectory(); await appBridge.chooseReceiveDirectory(); await appBridge.completeOnboarding(onboarding); await appBridge.updateSettings(settings); await appBridge.enqueuePaths(['C:\\a'], ['d']); await appBridge.requestPairing(pairing); await appBridge.startPairingAtEndpoint('192.168.1.5:48721'); await appBridge.confirmPairing('p'); await appBridge.rejectPairing('p'); await appBridge.cancelBatch('b'); await appBridge.retryBatch('b'); await appBridge.showMainWindow(); await appBridge.quitApp(); expect(invoke.mock.calls).toEqual([['get_app_snapshot'], ['choose_files'], ['choose_directory'], ['choose_receive_directory'], ['complete_onboarding', { input: onboarding }], ['update_settings', { input: settings }], ['enqueue_paths', { input: { paths: ['C:\\a'], targetDeviceIds: ['d'], queueOffline: false } }], ['request_pairing', { input: pairing }], ['start_pairing_at_endpoint', { input: { endpoint: '192.168.1.5:48721' } }], ['confirm_pairing', { input: { pairingId: 'p' } }], ['reject_pairing', { input: { pairingId: 'p' } }], ['cancel_batch', { input: { batchId: 'b' } }], ['retry_batch', { input: { batchId: 'b' } }], ['show_main_window'], ['quit_app']]); });
  it('can request offline queueing with the exact command payload', async () => { await appBridge.enqueuePaths(['C:\\a'], ['d'], true); expect(invoke).toHaveBeenCalledWith('enqueue_paths', { input: { paths: ['C:\\a'], targetDeviceIds: ['d'], queueOffline: true } }); });
  it('uses exact settings, View logs, and Export logs contracts without caller paths', async () => { await appBridge.updateSettings({ listenAddress: '127.0.0.1:48721', historyRetentionDays: 90 }); await appBridge.viewLogs(); await appBridge.exportLogs(); expect(invoke.mock.calls).toEqual([['update_settings', { input: { listenAddress: '127.0.0.1:48721', historyRetentionDays: 90 } }], ['view_logs'], ['export_logs']]); });
  it('starts discovery pairing and local rename with durable IDs only', async () => { await appBridge.startPairingDiscovered('nearby-1'); await appBridge.renameTrustedDevice('device-1', 'Office laptop'); expect(invoke.mock.calls).toEqual([['start_pairing_discovered', { input: { deviceId: 'nearby-1' } }], ['rename_trusted_device', { input: { deviceId: 'device-1', alias: 'Office laptop' } }]]); });
  it('uses durable IDs, never caller paths, for native completed-output actions', async () => { await appBridge.revealCompletedBatch('batch-1'); await appBridge.copyCompletedBatch('batch-1'); await appBridge.moveCompletedBatch('batch-1'); await appBridge.revealItem('item-1'); await appBridge.copyItem('item-1'); await appBridge.moveItem('item-1'); expect(invoke.mock.calls).toEqual([['reveal_completed_batch', { input: { batchId: 'batch-1' } }], ['copy_completed_batch', { input: { batchId: 'batch-1' } }], ['move_completed_batch', { input: { batchId: 'batch-1' } }], ['reveal_item', { input: { itemId: 'item-1' } }], ['copy_item', { input: { itemId: 'item-1' } }], ['move_item', { input: { itemId: 'item-1' } }]]); });
  it('subscribes to the exposed native, snapshot, and navigation channels', async () => { const snapshot = vi.fn(); const drop = vi.fn(); const navigate = vi.fn(); await appBridge.listenForNativeDrop(drop); await appBridge.listenForSnapshotChanges(snapshot); await appBridge.listenForNavigation(navigate); expect(listen.mock.calls.map(([name]) => name)).toEqual(['tauri://drag-drop', 'app://snapshot-changed', 'app://navigate']); });
});
