import { ChevronDown } from 'lucide-react';
import { useState } from 'react';
import { appBridge } from '../lib/bridge';
import { formatPeer, formatWhen } from '../lib/format';
import { StatusPill } from './StatusPill';
import type { AppSnapshotViewModel, BackendAppSnapshot, HistoryItemViewModel, HistoryTopLevelItemViewModel, TransferBatchViewModel, TrustedDeviceViewModel } from '../types/view-models';

export function ActivityView({ snapshot, onSnapshot }: { snapshot: AppSnapshotViewModel; onSnapshot: (snapshot: BackendAppSnapshot) => void }) {
  return <section className="tab-panel" aria-labelledby="activity-heading"><div className="panel-heading"><div><h1 id="activity-heading">Activity</h1><p>Sending and received files, newest first.</p></div></div>{snapshot.transfers.length > 0 && <section className="activity-section"><h2>Transfers</h2>{snapshot.transfers.map((batch) => <TransferCard key={batch.id} batch={batch} onSnapshot={onSnapshot} />)}</section>}<section className="activity-section"><h2>History</h2>{snapshot.history.length ? snapshot.history.map((item) => <HistoryRow item={item} trusted={snapshot.trustedDevices} key={item.id} />) : <div className="empty-activity"><strong>Nothing here yet</strong><span>Transfers you send and receive will appear here.</span></div>}</section></section>;
}

function TransferCard({ batch, onSnapshot }: { batch: TransferBatchViewModel; onSnapshot: (snapshot: BackendAppSnapshot) => void }) { const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const canCancel = ['queued', 'preparing', 'sending', 'verifying'].includes(batch.state); const canRetry = batch.state === 'failed'; async function act(action: 'cancel' | 'retry') { setBusy(true); setError(null); try { onSnapshot(action === 'cancel' ? await appBridge.cancelBatch(batch.id) : await appBridge.retryBatch(batch.id)); } catch { setError(action === 'cancel' ? 'Fileporter could not cancel this transfer.' : 'Fileporter could not retry this transfer.'); } finally { setBusy(false); } } return <article className="transfer-card"><div><strong>{batch.label}</strong><StatusPill state={batch.state} /></div><progress value={batch.progress} max="100">{batch.progress}%</progress>{batch.targets.map((target) => <div className="target-row" key={target.id}><span>{target.deviceName}</span><span>{target.rateLabel ?? ''}</span><StatusPill state={target.state} /></div>)}{(canCancel || canRetry) && <div className="transfer-actions">{canCancel && <button type="button" disabled={busy} onClick={() => { void act('cancel'); }}>Cancel transfer</button>}{canRetry && <button type="button" disabled={busy} onClick={() => { void act('retry'); }}>Retry transfer</button>}</div>}{error && <p className="form-error" role="alert">{error}</p>}</article>; }

type NativeAction = 'reveal' | 'copy' | 'move';
function success(action: NativeAction, subject: string) { return action === 'move' ? `${subject} are ready to move. Paste them in your file manager to complete the move.` : action === 'copy' ? `${subject} are ready to paste from the system file clipboard.` : `${subject} were revealed in your file manager.`; }
function failure(action: NativeAction, subject: string) { return action === 'move' ? `Fileporter could not prepare ${subject.toLowerCase()} for moving.` : action === 'copy' ? `Fileporter could not copy ${subject.toLowerCase()}.` : `Fileporter could not reveal ${subject.toLowerCase()}.`; }

function HistoryRow({ item, trusted }: { item: HistoryItemViewModel; trusted: TrustedDeviceViewModel[] }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [status, setStatus] = useState<string | null>(null);
  const canAct = item.direction === 'incoming' && item.state === 'complete';
  async function actBatch(action: NativeAction) { setBusy(true); setError(null); setStatus(null); try { if (action === 'reveal') await appBridge.revealCompletedBatch(item.id); else if (action === 'copy') await appBridge.copyCompletedBatch(item.id); else await appBridge.moveCompletedBatch(item.id); setStatus(success(action, 'Completed files')); } catch { setError(failure(action, 'completed files')); } finally { setBusy(false); } }
  async function actItem(action: NativeAction, output: HistoryTopLevelItemViewModel) { setBusy(true); setError(null); setStatus(null); try { if (action === 'reveal') await appBridge.revealItem(output.itemId); else if (action === 'copy') await appBridge.copyItem(output.itemId); else await appBridge.moveItem(output.itemId); setStatus(success(action, output.displayName)); } catch { setError(failure(action, output.displayName)); } finally { setBusy(false); } }
  return <article className="history-card"><button className="history-summary" type="button" aria-expanded={open} onClick={() => setOpen((value) => !value)}><ChevronDown className={open ? 'chevron-open' : ''} size={17} /><span>{item.direction === 'incoming' ? 'Received from' : 'Sent to'} <strong>{formatPeer(item.peerName, trusted)}</strong></span><span>{item.summary}</span><span>{formatWhen(item.timeLabel)}</span><StatusPill state={item.state} /></button>{open && <div className="received-items">{canAct ? <><div className="action-row"><button type="button" disabled={busy} onClick={() => { void actBatch('reveal'); }}>Reveal completed files</button><button type="button" disabled={busy} onClick={() => { void actBatch('copy'); }}>Copy completed files</button><button type="button" disabled={busy} onClick={() => { void actBatch('move'); }}>Move completed files</button></div><p className="muted">Move prepares the system file clipboard. Paste in your file manager to complete the move.</p><div className="received-item-list" aria-label="Received top-level items">{item.items.map((output) => <div className="received-item" key={output.itemId}><div><strong>{output.displayName}</strong><span className="muted">{output.kind} · {output.size} bytes{output.destinationLabel ? ` · Saved to ${output.destinationLabel}` : ''}</span></div>{output.available ? <div className="action-row"><button type="button" className="inline-action" disabled={busy} onClick={() => { void actItem('reveal', output); }}>Reveal {output.displayName}</button><button type="button" className="inline-action" disabled={busy} onClick={() => { void actItem('copy', output); }}>Copy {output.displayName}</button><button type="button" className="inline-action" disabled={busy} onClick={() => { void actItem('move', output); }}>Move {output.displayName}</button></div> : <span className="unavailable">Unavailable — this completed item was moved or deleted.</span>}</div>)}</div></> : <p className="muted">Native file actions are available only for completed incoming transfers.</p>}{status && <p className="muted" role="status">{status}</p>}{error && <p className="form-error" role="alert">{error}</p>}</div>}</article>;
}
