import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import App from '../App';
import { appBridge } from '../lib/bridge';
import type { BackendAppSnapshot } from '../types/view-models';

const base: BackendAppSnapshot = { revision: 4, lifecycle: { windowVisible: true, receivingEnabled: true, listening: false, receiving: false, shuttingDown: false }, settings: { deviceName: 'Desk', receiveDirectory: 'C:\\Incoming', onboardingComplete: true, launchAtLogin: true, notificationsEnabled: true, receivingEnabled: true, preferredListenAddress: '127.0.0.1:48721', preferredListenPort: 48721, historyRetentionDays: 30 }, managersStarted: true, localDeviceName: 'Desk', devices: [], nearbyDevices: [], transfers: [], history: [], queuedBatches: [], pairing: { localDeviceId: 'local', pendingPairings: [], trustedDevices: [] }, network: { listening: false, boundEndpoint: null, preferredListenAddress: '127.0.0.1:48721', trustedOnlineEndpoints: [], mdnsState: 'stopped', localInterfaceSummaries: [], recentErrorCodes: [] }, about: { appVersion: '0.1.0', protocolVersion: 1, logsAvailable: true, databaseMigrationVersion: 8, ownedStagingBytes: 0 } };
beforeEach(() => { vi.restoreAllMocks(); vi.spyOn(appBridge, 'listenForNativeDrop').mockResolvedValue(() => undefined); vi.spyOn(appBridge, 'listenForSnapshotChanges').mockResolvedValue(() => undefined); });

it('confirms a pending record with its backend pairingId payload', async () => { vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue({ ...base, pairing: { ...base.pairing, pendingPairings: [{ id: 'pairing-1', deviceId: 'device-1', remoteName: 'Laptop', certificateFingerprint: 'abc', expiresAt: 99, localConfirmed: false, remoteConfirmed: false, sasCode: '042 007' }] } }); const confirm = vi.spyOn(appBridge, 'confirmPairing').mockResolvedValue({ pairing: { id: 'pairing-1', deviceId: 'device-1', remoteName: 'Laptop', certificateFingerprint: 'abc', expiresAt: 99, localConfirmed: true, remoteConfirmed: false, sasCode: '042 007' }, trustedDevice: null }); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Devices' })); fireEvent.click(await screen.findByRole('button', { name: 'Confirm pairing' })); await waitFor(() => expect(confirm).toHaveBeenCalledWith('pairing-1')); });
it('keeps confirmation disabled until the backend supplies a matching SAS code', async () => { vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue({ ...base, pairing: { ...base.pairing, pendingPairings: [{ id: 'pairing-1', deviceId: 'device-1', remoteName: 'Laptop', certificateFingerprint: 'abc', expiresAt: 99, localConfirmed: false, remoteConfirmed: false, sasCode: null }] } }); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Devices' })); expect(await screen.findByRole('button', { name: 'Confirm pairing' })).toBeDisabled(); expect(screen.getByRole('status')).toHaveTextContent('Waiting for a matching security code'); });
it('forgets a trusted device with its backend deviceId payload', async () => { vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue({ ...base, pairing: { ...base.pairing, trustedDevices: [{ deviceId: 'device-1', name: 'Laptop', alias: null, pairedAt: 99, lastSeenAt: null, certificateFingerprintShort: 'ABCD', autoSend: true, endpoint: null }] } }); const forget = vi.spyOn(appBridge, 'forgetDevice').mockResolvedValue(); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Devices' })); fireEvent.click(await screen.findByRole('button', { name: 'Forget' })); await waitFor(() => expect(forget).toHaveBeenCalledWith('device-1')); });
it('starts manual pairing with the exact endpoint input and reports failure accessibly', async () => { vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue(base); const start = vi.spyOn(appBridge, 'startPairingAtEndpoint').mockRejectedValue(new Error('unreachable')); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Devices' })); fireEvent.change(screen.getByLabelText('Private endpoint'), { target: { value: '192.168.1.24:48721' } }); fireEvent.click(screen.getByRole('button', { name: 'Start pairing' })); await waitFor(() => expect(start).toHaveBeenCalledWith('192.168.1.24:48721')); expect(screen.getByRole('alert')).toHaveTextContent('could not start pairing'); });
it('pairs a nearby candidate by stored device ID and locally renames a trusted device', async () => { const snapshot = { ...base, nearbyDevices: [{ deviceId: 'nearby-1', displayName: 'Studio Mac', endpoint: '192.168.1.8:48721', certificateFingerprint: 'fp', protocolVersion: 1, capabilities: [] }], pairing: { ...base.pairing, trustedDevices: [{ deviceId: 'device-1', name: 'Laptop', alias: null, pairedAt: 1, lastSeenAt: null, certificateFingerprintShort: 'ABCD', autoSend: true, endpoint: null }] } }; vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue(snapshot); const pair = vi.spyOn(appBridge, 'startPairingDiscovered').mockResolvedValue({ id: 'pair-1', deviceId: 'nearby-1', remoteName: 'Studio Mac', certificateFingerprint: 'fp', expiresAt: 9, localConfirmed: false, remoteConfirmed: false, sasCode: null }); const rename = vi.spyOn(appBridge, 'renameTrustedDevice').mockResolvedValue(); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Devices' })); fireEvent.click(screen.getByRole('button', { name: 'Pair' })); await waitFor(() => expect(pair).toHaveBeenCalledWith('nearby-1')); fireEvent.click(screen.getByRole('button', { name: 'Rename locally' })); fireEvent.change(screen.getByLabelText('Local name for Laptop'), { target: { value: 'Office laptop' } }); fireEvent.click(screen.getByRole('button', { name: 'Save name' })); await waitFor(() => expect(rename).toHaveBeenCalledWith('device-1', 'Office laptop')); });
it('cancels active batches and retries failed batches with batchId payloads', async () => { const transfers = [{ id: 'active', label: 'Photo', state: 'sending' as const, progress: 30, targets: [] }, { id: 'failed', label: 'Archive', state: 'failed' as const, progress: 10, targets: [] }]; vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue({ ...base, transfers }); const cancel = vi.spyOn(appBridge, 'cancelBatch').mockResolvedValue({ ...base, revision: 5, transfers }); const retry = vi.spyOn(appBridge, 'retryBatch').mockResolvedValue({ ...base, revision: 6, transfers }); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Activity' })); fireEvent.click(screen.getByRole('button', { name: 'Cancel transfer' })); await waitFor(() => expect(cancel).toHaveBeenCalledWith('active')); fireEvent.click(screen.getByRole('button', { name: 'Retry transfer' })); await waitFor(() => expect(retry).toHaveBeenCalledWith('failed')); });
it('uses stored item IDs for nested completed-output actions and explains unavailable records', async () => { const history = [{ id: 'batch-1', direction: 'incoming' as const, peerName: 'Laptop', summary: '2 files', timeLabel: 'Now', state: 'complete' as const, items: [{ itemId: 'item-1', displayName: 'photo.jpg', kind: 'file', size: 12, state: 'complete' as const, available: true }, { itemId: 'item-2', displayName: 'gone.txt', kind: 'file', size: 3, state: 'complete' as const, available: false }] }]; vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue({ ...base, history }); const move = vi.spyOn(appBridge, 'moveItem').mockResolvedValue(); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Activity' })); fireEvent.click(screen.getByRole('button', { name: /Received from Laptop/ })); fireEvent.click(screen.getByRole('button', { name: 'Move photo.jpg' })); await waitFor(() => expect(move).toHaveBeenCalledWith('item-1')); expect(screen.getByText(/gone.txt/)).toBeVisible(); expect(screen.getByText(/was moved or deleted/)).toBeVisible(); });
it('prepares a completed incoming batch for moving with its stored ID and reports the outcome accessibly', async () => { const history = [{ id: 'batch-1', direction: 'incoming' as const, peerName: 'Laptop', summary: '1 file', timeLabel: 'Now', state: 'complete' as const, items: [] }]; vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue({ ...base, history }); const move = vi.spyOn(appBridge, 'moveCompletedBatch').mockResolvedValue(); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Activity' })); fireEvent.click(screen.getByRole('button', { name: /Received from Laptop/ })); fireEvent.click(screen.getByRole('button', { name: 'Move completed files' })); await waitFor(() => expect(move).toHaveBeenCalledWith('batch-1')); expect(screen.getByRole('status')).toHaveTextContent('ready to move'); });
it('reports a move preparation error accessibly', async () => { const history = [{ id: 'batch-1', direction: 'incoming' as const, peerName: 'Laptop', summary: '1 file', timeLabel: 'Now', state: 'complete' as const, items: [] }]; vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue({ ...base, history }); vi.spyOn(appBridge, 'moveCompletedBatch').mockRejectedValue(new Error('clipboard unavailable')); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Activity' })); fireEvent.click(screen.getByRole('button', { name: /Received from Laptop/ })); fireEvent.click(screen.getByRole('button', { name: 'Move completed files' })); expect(await screen.findByRole('alert')).toHaveTextContent('could not prepare'); });
it('keeps clipboard and reveal controls hidden while offering endpoint pairing', async () => { vi.spyOn(appBridge, 'getAppSnapshot').mockResolvedValue(base); render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Devices' })); expect(screen.getByRole('button', { name: 'Start pairing' })).toBeVisible(); expect(screen.queryByRole('button', { name: /Copy|Cut|Show/i })).not.toBeInTheDocument(); });
